language: java

jdk:
  - oraclejdk8

branches:
  only:
    - 2.5.1

sudo: true

cache:
  apt: true
  directories:
    - $HOME/.m2

install:
  -

script:
  - mvn clean compile -q 
  #- travis_wait 60 mvn clean compile -q 
