language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
sudo: false
notifications:
  email:
    recipients:
      - speck@informatik.uni-leipzig.de
    on_success: change
    on_failure: change
