language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

sudo: true

cache:
  apt: true
  directories:
    - ~/.m2

install:
    - true

script: mvn clean compile -DskipTests=true

notifications:
  email:
    recipients:
      - speck@informatik.uni-leipzig.de
    on_success: change
    on_failure: change