language: java

jdk:
  - oraclejdk8

branches:
  only:
    - 2.5.1

sudo: true

cache:
  apt: true
  directories:
    - $HOME/.m2

install:
  -

script:
  - travis_wait 60 mvn clean compile

notifications:
  email:
    recipients:
      - speck@informatik.uni-leipzig.de
    on_success: change
    on_failure: change
